app:
    resource: AppBundle\Controller\DefaultController
    type:     annotation

api:
    type:     rest
    host:     symfony.dev
    resource: AppBundle\Controller\EmailController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"